# Generated by Django 4.1.7 on 2023-04-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_stock_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='stock_history_log',
            name='phone_number',
        ),
    ]
