# Generated by Django 4.1.7 on 2023-04-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_stock_updated_by_stock_history_log_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='low_stock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
