# Generated by Django 4.1.7 on 2023-04-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_stock_low_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='low_stock',
        ),
    ]
